name: template-build

on:
  push:
    branches: [ "develop" ]
    # paths:
    #   - 'cloudscribeTemplate/**'
    #   - 'Content/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: nuget/setup-nuget@v2
      with:
        nuget-version: 'latest'
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build NuGet package locally and test in at least 6 different configurations
      run: ./testtemplates.sh || (echo "At least one test failed!" && exit 1)
    - name: Setup NuGet
      run: dotnet nuget add source ${{ secrets.NUGET_SOURCE_URL }} -u ${{secrets.NUGET_USERNAME }} -p ${{ secrets.NUGET_PASSWORD }} --store-password-in-clear-text
    - name: Publish Template nupkg
      run: dotnet nuget push ./nupkgs/*.nupkg --source ${{ secrets.NUGET_SOURCE_URL }} || (echo "Failed to publish NUGET!" && exit 1)
    - name: Remote Repository Dispatch
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.GHB_PAT }}
        repository: GreatHouseBarn/cloudscribe-testing
        event-type: template-build
